Repository FRONT-END-BOOTCAMP-PLUS-3/fungle, pull requests merged in 2025-03, with the labels that each got.

#188 [design] 마이페이지 UI 디자인 #168
  app/user/MyPage.styled.tsx
  app/user/components/PostAndLikedListWrapper.styled.tsx
  app/user/components/ProfileInfo.styled.tsx
  app/user/components/ProfileInfo.tsx
  app/user/components/ProfileIntroduce.styled.tsx
  app/user/components/ProfileIntroduce.tsx
  app/user/components/ProfileLikedList.tsx
  app/user/components/ProfileMenu.styled.tsx
  app/user/components/ProfileMenu.tsx
  app/user/components/ProfileNovelList.styled.tsx
  app/user/components/ProfileNovelList.tsx
  app/user/components/ProfilePostList.tsx
  app/user/components/ProfileView.styled.tsx
  app/user/components/ProfileView.tsx
  app/user/page.tsx
  constants/USER_INFO_LIST.ts
Labels: 🎨 Design

#191 [feat] 커뮤니티 게시글 작성 기능 구현 #27
  app/api/community/create/route.ts
  app/user/community/components/CommunityListFilter.tsx
  app/user/community/components/CommunityPostForm.tsx
  app/user/community/components/CommunityPostList.tsx
  app/user/community/create/page.tsx
  application/usecases/community/DfPostCreateUsecase.ts
  application/usecases/community/dto/PostCreateDto.ts
  domain/repositories/CommunityPostRepository.ts
  infrastructure/repositories/PrCommunityPostRepository.ts
  prisma/schema.prisma
Labels: ✨ Feat, ♻️ Refactor, 📀 Database

#189 [Feat] 책 생성 BE #179
  app/api/novel/[novelId]/route.ts
  app/api/novel/route.ts
  app/user/novel/create/page.tsx
  application/usecases/novel/DfCreateNovelUsecase.ts
  application/usecases/novel/dto/CreateNovel.ts
  application/usecases/novel/dto/NovelResponse.ts
  constants/STATUS.ts
  domain/repositories/GenreRepository.ts
  domain/repositories/NovelRepository.ts
  hooks/useAuth.ts
  infrastructure/config/novelDi.ts
  infrastructure/repositories/PrGenreRepository.ts
  infrastructure/repositories/PrNovelRepostiory.ts
  infrastructure/services/FileService.ts
  next.config.ts
  public/bookCover/1740912955011-jojobook.jpg
  public/image/jojoprofile.jpeg
Labels: ✨ Feat

#193 [refactor] 03/02 함수 화살표 함수로 변경 #192
  app/api/novel/[novelId]/route.ts
  application/usecases/novel/DfCreateNovelUsecase.ts
  application/usecases/novel/DfEpisodeByIdUseCase.ts
  application/usecases/novel/DfEpisodesByNovelIdUseCase.ts
  application/usecases/novel/DfNovelUsecase.ts
  application/usecases/novel/dto/NovelEpisode.ts
Labels: ♻️ Refactor

#196 [feat] 로그인 상태 관리 zustand로 변경 #190
  app/(anon)/login/actions/loginProc.ts
  app/(anon)/login/page.tsx
  app/layout.tsx
  app/user/components/ProfileIntroduce.styled.tsx
  app/user/components/ProfileIntroduce.tsx
  app/user/components/ProfileNovelList.tsx
  app/user/components/ProfileView.tsx
  application/usecases/auth/DfLoginUsecase.ts
  application/usecases/auth/DfVerifyRefreshToken.ts
  application/usecases/auth/dto/LoginResponseDto.ts
  components/authInitializer/AuthInitializer.tsx
  context/AuthContext.tsx
  hooks/useAuth.ts
  middleware.ts
  store/useAuthStore.ts
Labels: ✨ Feat

#200 [feat] 닉네임 수정 api 구현
  app/api/user/nickname/route.ts
  app/user/components/ProfileView.styled.tsx
  app/user/components/ProfileView.tsx
  application/usecases/user/DfUpdateNicknameUsecase.ts
  application/usecases/user/error/NicknameError.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/PrUserRepository.ts
Labels: ✨ Feat

#202 [feat] 소설 에피소드 연재 #194
  app/api/novel/[novelId]/episode/route.ts
  app/api/novel/[novelId]/route.ts
  app/api/novel/route.ts
  app/user/novel/[novelId]/(episode)/[episodeId]/page.tsx
  app/user/novel/[novelId]/page.tsx
  app/user/novel/create/component/ConfirmationModal.tsx
  app/user/novel/create/page.tsx
  app/user/novel/serialize/[novelId]/page.tsx
  application/usecases/novel/DfCreateEpisodeUsecase.ts
  application/usecases/novel/DfEpisodesByNovelIdUseCase.ts
  application/usecases/novel/DfNovelUsecase.ts
  application/usecases/novel/dto/NovelEpisode.ts
  domain/repositories/NovelEpisodeRepository.ts
  infrastructure/config/novelDi.ts
  infrastructure/repositories/PrNovelEpisodeRepository.ts
Labels: ✨ Feat

#195 [feat] 커뮤니티 게시글 수정 기능 구현 #32
  app/api/community/[id]/edit/route.ts
  app/api/community/[id]/update/route.ts
  app/user/community/[id]/edit/components/CommunityEdit.styled.tsx
  app/user/community/[id]/edit/components/CommunityEdit.tsx
  app/user/community/[id]/edit/page.tsx
  app/user/community/components/CommunityPostForm.tsx
  app/user/community/create/page.tsx
  application/usecases/community/DfGetPostWithRecruitmentsUsecase.ts
  application/usecases/community/DfPostDetailUsecase.ts
  application/usecases/community/DfPostUpdateUsecase.ts
  application/usecases/community/dto/GetPostWithRecruitmentsDto.ts
  application/usecases/community/dto/PostUpdateDto.ts
  domain/repositories/CommunityPostRepository.ts
  infrastructure/repositories/PrCommunityPostRepository.ts
Labels: ✨ Feat, ♻️ Refactor

#204 [fix]소설 페이지 장르,연재일, 연재상태 영어 -> 한글 전환 #203
  app/user/novel/[novelId]/page.tsx
Labels: 🛠️ Fix

#201 회원가입 - 이메일 인증하기 기능 구현
  app/(anon)/signup/components/EmailVerification.tsx
  app/api/auth/send-email/route.ts
  app/api/auth/verify-code/route.ts
  application/usecases/auth/DfCheckVerificationCodeUsecase.ts
  infrastructure/repositories/IMVerificationRepository.ts
  infrastructure/repositories/PrVerificationRepository.ts
Labels: ✨ Feat, 💄 Style

#209 [refactor] 커뮤니티 api/route refactor #205
  app/api/community/[id]/comments/route.ts
  app/api/community/[id]/route.ts
  app/api/community/[id]/update/route.ts
  app/api/community/create/route.ts
  application/usecases/community/DfPostDetailCommentUsecase.ts
  application/usecases/community/DfPostDetailUsecase.ts
  domain/repositories/CommunityCommentRepository.ts
  domain/repositories/CommunityPostRepository.ts
  infrastructure/repositories/PrCommunityCommentRepository.ts
  infrastructure/repositories/PrCommunityPostRepository.ts
Labels: ♻️ Refactor

#213 [fix] novel approved 만 보여주기
  app/api/novel/[novelId]/[episodeId]/route.ts
  app/api/novel/[novelId]/route.ts
  infrastructure/repositories/PrNovelEpisodeRepository.ts
Labels: 🛠️ Fix

#215 [feat] 소설 조회수
  app/api/novel/[novelId]/[episodeId]/route.ts
  app/user/novel/[novelId]/(episode)/[episodeId]/page.tsx
  application/usecases/novel/DfIncreaseViewCountUsecase.ts
  application/usecases/novel/dto/NovelEpisode.ts
  domain/repositories/NovelEpisodeRepository.ts
  infrastructure/config/novelDi.ts
  infrastructure/repositories/PrNovelEpisodeRepository.ts
Labels: ✨ Feat

#216 [feat] 커뮤니티 게시글 삭제 기능 구현 #33
  app/api/community/[id]/route.ts
  app/api/community/[id]/update/route.ts
  app/user/community/[id]/components/CommunityPostHeader.tsx
  application/usecases/community/DfPostDeleteUsecase.ts
  application/usecases/community/dto/PostDeleteDto.ts
  domain/repositories/CommunityPostRepository.ts
  infrastructure/repositories/PrCommunityPostRepository.ts
Labels: ✨ Feat

#220 [design] novel page 사진 찌그러짐 수정
  app/user/novel/[novelId]/(episode)/[episodeId]/EpisodePage.styled.tsx
  app/user/novel/[novelId]/NovelIdPage.styled.tsx
  app/user/novel/[novelId]/page.tsx
Labels: 🛠️ Fix, 🎨 Design

#217 [feat] 라우터 연결
  app/api/auth/register/route.ts
  application/usecases/auth/DfSignupUsecase.ts
Labels: ✨ Feat

#219 [feat] 사용자 프로필 사진 수정 api 구현 #208
  app/api/auth/refresh/route.ts
  app/api/user/profile-image/route.ts
  app/user/components/ProfileView.styled.tsx
  app/user/components/ProfileView.tsx
  application/usecases/auth/DfRefreshTokenUsecase.ts
  application/usecases/user/DfUpdateProfileImageUsecase.ts
  application/usecases/user/dto/UpdateProfileImage.ts
  domain/repositories/UserRepository.ts
  infrastructure/repositories/PrUserRepository.ts
  infrastructure/services/FileService.ts
Labels: ✨ Feat

#224 [feat] 회원가입 페이지 UI 개선 #222
  app/(anon)/signup/Signup.styled.tsx
  app/(anon)/signup/components/EmailVerification.tsx
Labels: ✨ Feat

#223 [feat] 커뮤니티 게시글 좋아요 기능 구현 #36
  app/api/community/like/route.ts
  app/user/community/[id]/components/CommunityPostContent.tsx
  application/usecases/community/DfPostDetailUsecase.ts
  application/usecases/community/DfTogglePostLikeUsecase.ts
  application/usecases/community/dto/CommunityPostWithNicknameAndLikesDto.ts
  application/usecases/community/dto/ToggleLikeDto.ts
  domain/repositories/CommunityPostLikeRepository.ts
  domain/repositories/CommunityPostRepository.ts
  infrastructure/repositories/PrCommunityPostLikeRepository.ts
  infrastructure/repositories/PrCommunityPostRepository.ts
Labels: ✨ Feat

#234 [feat] 커뮤니티 게시글 댓글 개수 불러오기 기능 구현 #233
  app/api/community/comment/[id]/route.ts
  app/user/community/[id]/page.tsx
  application/usecases/comment/DfCommentCountUsecase.ts
  components/comment/CommentCreate.tsx
  components/comment/CommentHeader.styled.tsx
  components/comment/CommentHeader.tsx
  domain/repositories/CommunityCommentRepository.ts
  infrastructure/repositories/PrCommunityCommentRepository.ts
Labels: ✨ Feat, 🎨 Design

#236 [feat] userId로 소설, 에피소드 조회 구현 #229
  app/api/user/novel/route.ts
  app/user/components/ProfileNovelList.styled.tsx
  app/user/components/ProfileNovelList.tsx
  application/usecases/novel/DfEpisodeByUserIdUsecase.ts
  application/usecases/novel/DfNovelByUserIdUsecase.ts
  application/usecases/novel/dto/NovelEpisodesByUserId.ts
  application/usecases/novel/dto/NovelsByUserId.ts
  constants/EPISODE_STATUS.ts
  domain/repositories/NovelEpisodeRepository.ts
  domain/repositories/NovelRepository.ts
  infrastructure/repositories/PrNovelEpisodeRepository.ts
  infrastructure/repositories/PrNovelRepostiory.ts
Labels: ✨ Feat, 🎨 Design

#237 [Design] 소설 메인페이지
  app/user/novel/NovelPage.styled.tsx
  app/user/novel/component/BannerCarousel.tsx
  app/user/novel/component/FloatingButton.styled.tsx
  app/user/novel/component/FloatingButton.tsx
  app/user/novel/component/MyBook.styled.tsx
  app/user/novel/component/MyBook.tsx
  app/user/novel/component/SearchBook.styled.tsx
  app/user/novel/component/SearchBook.tsx
  app/user/novel/component/SerialDayBook.styled.tsx
  app/user/novel/component/SerialDayBook.tsx
  app/user/novel/component/Top10.styled.tsx
  app/user/novel/component/Top10.tsx
  app/user/novel/page.tsx
  application/usecases/novel/DfCreateNovelUsecase.ts
  application/usecases/novel/DfEpisodeByIdUseCase.ts
  components/progressbar/ProgressBar.styled.tsx
  components/progressbar/ProgressBar.tsx
  constants/SEARCH_OPTIONS.ts
  infrastructure/config/novelDi.ts
  package-lock.json
  package.json
  public/banner/badboyBanner.svg
  public/banner/manimBanner.svg
  public/banner/napoliBanner.svg
  public/icon/floating_close.svg
Labels: 🎨 Design

#238 [design] 03/05 anon novel page 생성 #182
  app/(anon)/novel/page.tsx
Labels: 🎨 Design

#241 [feat] novel 좋아요
  app/api/novel/like/route.ts
  app/user/novel/[novelId]/page.tsx
  app/user/novel/component/NovelLikeButton.styled.tsx
  app/user/novel/component/NovelLikeButton.tsx
  application/usecases/novel/DfToggleNovelLikeUsecase.ts
  application/usecases/novel/dto/ToggleNovelLike.ts
  domain/repositories/NoveLikeRepository.ts
  infrastructure/repositories/PrNovelLikeRepository.ts
Labels: ✨ Feat

#243 [feat] 사용자 아이디 가져오는 usecase 구현 #242
  app/api/user/nickname/route.ts
  app/api/user/novel/route.ts
  app/api/user/profile-image/route.ts
  application/usecases/auth/DfGetUserIdUsecase.ts
  infrastructure/config/userDi.ts
Labels: ✨ Feat

#246 [feat] 커뮤니티 댓글 수정 기능 구현 #28
  app/api/community/comment/[id]/route.ts
  app/user/community/[id]/components/CommunityPostHeader.tsx
  app/user/community/components/CommunityCommentEdit.styled.tsx
  app/user/community/components/CommunityCommentEdit.tsx
  app/user/community/components/MoreOptionMenu.tsx
  application/usecases/comment/DfCommentUpdateUsecase.ts
  components/comment/Comment.tsx
  components/comment/CommentHeader.tsx
  domain/repositories/CommunityCommentRepository.ts
  infrastructure/repositories/PrCommunityCommentRepository.ts
Labels: ✨ Feat

#248 [database] NovelEpisode 테이블 isFinalEpisode 컬럼 추가 #247
  prisma/schema.prisma
Labels: 📀 Database

#240 [feat] 마이페이지 커뮤니티 게시글 조회 및 모집 상태 변경 api 구현 #221
  app/api/user/community/route.ts
  app/api/user/introduce/route.ts
  app/api/user/nickname/route.ts
  app/api/user/profile-image/route.ts
  app/user/MyPage.styled.tsx
  app/user/components/PostAndLikedListWrapper.styled.tsx
  app/user/components/ProfileIntroduce.tsx
  app/user/components/ProfilePostList.tsx
  app/user/components/ProfileView.tsx
  application/usecases/community/DfPostDetailByUserIdUsecase.ts
  application/usecases/community/DfPostStatusUpdateUsecase.ts
  application/usecases/community/dto/PostWithRecruitmentDto.ts
  domain/repositories/CommunityPostRepository.ts
  infrastructure/repositories/PrCommunityPostRepository.ts
Labels: ✨ Feat

#251 [feat] novel 메인페이지 나의 소설 DB 연결
  app/user/novel/[novelId]/(episode)/[episodeId]/page.tsx
  app/user/novel/component/EmptyBookList.tsx
  app/user/novel/component/MyBook.styled.tsx
  app/user/novel/component/MyBook.tsx
  public/image/nobook.svg
Labels: ✨ Feat

#254 [feat] 소설 메인페이지 요일 별 연재
  app/api/novel/serial-day/[day]/route.ts
  app/user/novel/component/MyBook.styled.tsx
  app/user/novel/component/MyBook.tsx
  app/user/novel/component/SerialDayBook.styled.tsx
  app/user/novel/component/SerialDayBook.tsx
  application/usecases/novel/DfNovelsBySerialDayUsecase.ts
  application/usecases/novel/dto/SerialDayNovel.ts
  domain/repositories/NovelRepository.ts
  infrastructure/config/novelDi.ts
  infrastructure/repositories/PrNovelRepostiory.ts
Labels: ✨ Feat

#255 [design] 펀딩 UI
  app/user/funding/Funding.styled.tsx
  app/user/funding/page.tsx
  prisma/schema.prisma
Labels: ✨ Feat

#253 [feat] 커뮤니티 댓글 삭제 기능 구현 #29
  app/api/community/comment/[id]/route.ts
  application/usecases/comment/DfCommentDeleteUseccase.ts
  components/comment/Comment.tsx
  domain/repositories/CommunityCommentRepository.ts
  infrastructure/repositories/PrCommunityCommentRepository.ts
Labels: ✨ Feat

#257 [design] 03/06 이메일 형식 수정
  styles/email/sendEmailTemplate.tsx
Labels: 💄 Style

#260 [fix] 토큰 용도 수정 #250
  app/(anon)/login/actions/loginProc.ts
  app/api/auth/verify/route.ts
  app/api/community/[id]/route.ts
  app/api/community/[id]/update/route.ts
  app/api/community/comment/[id]/route.ts
  app/api/community/create/route.ts
  app/api/community/like/route.ts
  app/api/novel/like/route.ts
  app/api/user/community/route.ts
  app/api/user/introduce/route.ts
  app/api/user/nickname/route.ts
  app/api/user/novel/route.ts
  app/api/user/profile-image/route.ts
  app/user/components/ProfileIntroduce.tsx
  app/user/components/ProfileNovelList.tsx
  app/user/components/ProfilePostList.tsx
  app/user/components/ProfileView.tsx
  app/user/novel/component/NovelLikeButton.tsx
  app/user/novel/create/page.tsx
  application/usecases/auth/DfGetUserIdUsecase.ts
  application/usecases/auth/DfRefreshTokenUsecase.ts
  application/usecases/auth/DfVerifyAccessToken.ts
  infrastructure/config/novelDi.ts
  infrastructure/config/userDi.ts
  middleware.ts
  store/useAuthStore.ts
  utils/auth/jwt.ts
Labels: ✨ Feat

#262 [feat] banner DB 연결
  app/api/novel/banner/route.ts
  app/user/novel/component/BannerCarousel.tsx
  app/user/novel/component/BannerCorousel.styled.tsx
  application/usecases/novel/DfBannerNovelsUsecase.ts
  application/usecases/novel/dto/Banner.ts
  domain/repositories/NovelRepository.ts
  infrastructure/config/novelDi.ts
  infrastructure/repositories/PrNovelRepostiory.ts
Labels: ✨ Feat

#265 [refactor] 03/06 userId를 userDi.getUserIdUsecase.execute 불러오는 방식으로 변경
  app/api/community/[id]/comments/route.ts
  app/api/community/comment/[id]/like/route.ts
Labels: ♻️ Refactor

#269 [feat] 로그인 상태 저장 로직 수정 #268
  app/api/auth/verify/route.ts
  app/api/user/community/route.ts
  application/usecases/auth/DfGetUserIdUsecase.ts
  application/usecases/auth/DfRefreshTokenUsecase.ts
  application/usecases/auth/DfVerifyAccessToken.ts
  application/usecases/auth/DfVerifyAccessTokenUsecase.ts
  application/usecases/auth/dto/DecodedAccessToken.ts
  infrastructure/config/userDi.ts
  middleware.ts
  store/useAuthStore.ts
  utils/auth/jwt.ts
Labels: ✨ Feat

#271 [design] 03/07 소설 메인페이지 글자 wrap , 썸네일 크기 고정 #264
  app/user/novel/component/MyBook.styled.tsx
Labels: 🎨 Design

#273 [database] 03/07 Funding 테이블 title -> introduce 변경 #270
  prisma/schema.prisma
Labels: 📀 Database

#276 [database] 03/07 Funding 테이블 수정 #275
  prisma/schema.prisma
Labels: 📀 Database

#266 [feat] 소설 연재 상태 변경 #249
  app/api/community/[id]/update/route.ts
  app/api/user/novel/route.ts
  app/api/user/profile-image/route.ts
  app/user/components/ProfileNovelList.tsx
  app/user/components/ProfileView.styled.tsx
  app/user/components/ProfileView.tsx
  app/user/components/StatusUpdateButton.styled.tsx
  app/user/components/StatusUpdateButton.tsx
  application/usecases/funding/DfFundingUsecase.ts
  application/usecases/funding/dto/Funding.ts
  application/usecases/novel/DfDeleteNovelUsecase.ts
  application/usecases/novel/DfUpdateNovelSerialStatusUsecase.ts
  application/usecases/novel/dto/NovelsByUserId.ts
  application/usecases/user/DfUpdateProfileImageUsecase.ts
  constants/STATUS.ts
  domain/repositories/FundingRepository.ts
  domain/repositories/NovelRepository.ts
  infrastructure/repositories/PrFundingRepository.ts
  infrastructure/repositories/PrNovelRepostiory.ts
  infrastructure/services/FileService.ts
  public/bookCover/1741316494118-IMG_4407.jpeg
Labels: ✨ Feat

#279 [Fix] 소설 연재 시 체크박스에 isFinalEpisode, 완결된 소설 연재 방지
  app/api/novel/[novelId]/episode/route.ts
  app/user/novel/serialize/SerializePage.styled.tsx
  app/user/novel/serialize/[novelId]/page.tsx
  application/usecases/novel/DfCreateEpisodeUsecase.ts
  domain/repositories/NovelEpisodeRepository.ts
  infrastructure/repositories/PrNovelEpisodeRepository.ts
Labels: ✨ Feat

#277 [design] 마이페이지 좋아요 목록 드롭다운 구현 #267
  app/user/components/LikedNovelList.tsx
  app/user/components/LikedPostList.tsx
  app/user/components/PostAndLikedListWrapper.styled.tsx
  app/user/components/ProfileLikedList.tsx
  app/user/components/ProfileNovelList.styled.tsx
  constants/LIKED_OPTIONS.ts
Labels: 🎨 Design

#281 [design, feat] 요일별 연재 이미지 크기 조정, 오늘 요일로 랜더링
  app/user/novel/component/SerialDayBook.styled.tsx
  app/user/novel/component/SerialDayBook.tsx
Labels: ✨ Feat, 🎨 Design

#282 [Feat] 소설 메인페이지 top10
  app/api/novel/top10/route.ts
  app/user/novel/component/SerialDayBook.tsx
  app/user/novel/component/Top10.styled.tsx
  app/user/novel/component/Top10.tsx
  app/user/novel/page.tsx
  application/usecases/novel/DfTopNovelsUsecase.ts
  application/usecases/novel/dto/TopList.ts
  constants/GENRES.ts
  domain/repositories/NovelEpisodeRepository.ts
  domain/repositories/NovelRepository.ts
  infrastructure/config/novelDi.ts
  infrastructure/repositories/PrNovelEpisodeRepository.ts
  infrastructure/repositories/PrNovelRepostiory.ts
Labels: ✨ Feat

#284 [fix] 연재중인 소설이 있다면 소설 생성 금지
  app/user/novel/component/MyBook.styled.tsx
  app/user/novel/create/page.tsx
  application/usecases/novel/dto/NovelsByUserId.ts
Labels: 🛠️ Fix

#285 [feat] 좋아요 누른 목록 조회 #278
  app/api/user/community/liked/route.ts
  app/api/user/novel/liked/route.ts
  app/user/components/LikedNovelList.tsx
  app/user/components/LikedPostList.tsx
  application/usecases/auth/DfRefreshTokenUsecase.ts
  application/usecases/community/DfLikedCommunityPostsUsecase.ts
  application/usecases/novel/DfLikedNovelsUsecase.ts
  application/usecases/novel/dto/LikedNovel.ts
  domain/repositories/CommunityPostLikeRepository.ts
  domain/repositories/NoveLikeRepository.ts
  infrastructure/repositories/PrCommunityPostLikeRepository.ts
  infrastructure/repositories/PrNovelLikeRepository.ts
Labels: ✨ Feat

#288 [feat] 커뮤니티 대댓글 기능 구현 #274
  app/api/community/comment/[id]/route.ts
  app/user/community/[id]/page.tsx
  app/user/community/components/CommunityCommentEdit.tsx
  application/usecases/comment/DfCommentCreateUsecase.ts
  components/comment/Comment.styled.tsx
  components/comment/Comment.tsx
  components/comment/CommentCreateTextarea.tsx
  components/comment/CommentHeader.tsx
  components/comment/ReplyComment.styled.tsx
  components/comment/ReplyComment.tsx
  domain/repositories/CommunityCommentRepository.ts
  infrastructure/repositories/PrCommunityCommentRepository.ts
  public/icon/top_arrow.svg
Labels: ✨ Feat, ♻️ Refactor, 🎨 Design

#290 [feat] userId로 게시글, 소설 가져오는 BE 구현 및 api 연결 #287
  app/api/user/count/route.ts
  app/user/components/ProfileInfo.tsx
  application/usecases/user/DfGetUserStatsUsecase.ts
  application/usecases/user/dto/UserStats.ts
  domain/repositories/CommunityPostRepository.ts
  domain/repositories/NovelRepository.ts
  infrastructure/repositories/PrCommunityPostRepository.ts
  infrastructure/repositories/PrNovelRepostiory.ts
Labels: ✨ Feat

#289 [feat] 메인페이지 검색창
  app/api/novel/search/route.ts
  app/user/novel/component/SearchBook.styled.tsx
  app/user/novel/component/SearchBook.tsx
  app/user/novel/component/SearchResult.styled.tsx
  app/user/novel/component/SearchResults.tsx
  app/user/novel/component/SerialDayBook.styled.tsx
  app/user/novel/page.tsx
  application/usecases/novel/DfSearchNovelsUsecase.ts
  application/usecases/novel/dto/SearchNovel.ts
  constants/GENRES.ts
  domain/repositories/NovelGenreRepository.ts
  domain/repositories/NovelRepository.ts
  domain/repositories/UserRepository.ts
  infrastructure/config/novelDi.ts
  infrastructure/repositories/PrNovelGenreRepository.ts
  infrastructure/repositories/PrNovelRepostiory.ts
  infrastructure/repositories/PrUserRepository.ts
  public/image/searchnotfound.svg
Labels: ✨ Feat

#294 [feat] 로그아웃 기능 구현 #291
  app/api/logout/route.ts
  application/usecases/auth/DfLogoutUsecase.ts
  components/header/Header.tsx
  domain/repositories/AuthRepository.ts
  infrastructure/repositories/PrAuthRepository.ts
  infrastructure/repositories/PrNovelRepostiory.ts
  middleware.ts
Labels: ✨ Feat

#300 [feat] 연재중인 소설 있으면 연재 페이지로 리다이렉트
  app/user/novel/create/page.tsx
  application/usecases/novel/dto/OngoingNovel.ts
Labels: ✨ Feat

#303 [design] 메인페이지 소설 제목, 이미지 크기 고정
  app/user/novel/component/MyBook.styled.tsx
  app/user/novel/component/SerialDayBook.styled.tsx
  app/user/novel/component/Top10.styled.tsx
Labels: 🎨 Design

#309 [fix] top 10 리스트 요소 클릭 가능
  app/user/novel/[novelId]/(episode)/[episodeId]/page.tsx
  app/user/novel/component/Top10.styled.tsx
  app/user/novel/component/Top10.tsx
Labels: 🛠️ Fix

#302 [feat] 회원 탈퇴 기능 구현 #296
  app/api/user/delete/route.ts
  app/user/components/ProfileIntroduce.styled.tsx
  app/user/components/ProfileMoreOptions.styled.tsx
  app/user/components/ProfileMoreOptions.tsx
  app/user/components/ProfileView.styled.tsx
  app/user/components/ProfileView.tsx
  app/user/components/UserDeletionModal.styled.tsx
  app/user/components/UserDeletionModal.tsx
  application/usecases/user/DfDeleteUserUsecase.ts
  domain/repositories/UserRepository.ts
  infrastructure/config/userDi.ts
  infrastructure/repositories/PrUserRepository.ts
  infrastructure/services/FileService.ts
  middleware.ts
  public/bookCover/1741528524105-IMG_4417.jpeg
  store/useAuthStore.ts
Labels: ✨ Feat

#314 [database] NovelComment 테이블 parentId 추가 #313
  prisma/schema.prisma
Labels: 📀 Database

#306 [design] 03/10 하단 모달창 UI
  app/globals.css
  app/user/funding/components/FundingModal.styled.tsx
  app/user/funding/components/FundingModal.tsx
  app/user/funding/page.tsx
Labels: 🎨 Design

#320 [feat] 로그아웃 시 zustand로 관리하는 사용자 정보 변경 #298
  components/header/Header.styled.tsx
  components/header/Header.tsx
Labels: 🛠️ Fix

#322 [feat] 커뮤니티 리스트 페이지 네이션 이동 시 리스트 상단으로 스크롤 이동 구현 #316
  app/(main)/user/community/components/CommunityPostList.tsx
Labels: ✨ Feat

#325 [design] 커뮤니티 Loading 컴포넌트 작업 #323
  app/(main)/user/community/[id]/loading.tsx
  application/usecases/comment/DfCommentCountUsecase.ts
Labels: 💄 Style, 🎨 Design

#327 [refactor] 커뮤니티 상세 페이지 CSR로 변경 #326
  app/(main)/user/community/[id]/page.tsx
  app/(main)/user/community/components/CommunityPostList.tsx
  app/(main)/user/community/components/CommunitySearchFilter.tsx
  infrastructure/repositories/PrCommunityPostRepository.ts
Labels: ✨ Feat, ♻️ Refactor, 🔨Chore

#339 Style/banner img add
  public/banner/DueBanner.svg
  public/banner/shootBanner.svg
Labels: ✨ Feat

#336 [feat] 관리자 소설 검토 구현 #319
  app/(main)/layout.tsx
  app/admin/AdminPage.styled.tsx
  app/admin/layout.tsx
  app/admin/novel/AdminNovelPage.styled.tsx
  app/admin/novel/components/ApproveButton.tsx
  app/admin/novel/components/RejectionButton.tsx
  app/admin/novel/page.tsx
  app/api/admin/novel-episode/[episodeId]/route.ts
  app/api/admin/novel-episode/route.ts
  app/layout.tsx
  application/usecases/novel/DfDeleteNovelEpisodeUsecase.ts
  application/usecases/novel/DfNovelEpisodeWithUserInfoUsecase.ts
  application/usecases/novel/DfUpdateNovelEpisodeStatusUsecase.ts
  application/usecases/novel/dto/EpisodeWithUserInfo.ts
  application/usecases/novel/dto/NovelEpisodeWithUserInfo.ts
  domain/repositories/NovelEpisodeRepository.ts
  infrastructure/repositories/PrNovelEpisodeRepository.ts
  store/useAdminNovelStore.ts
Labels: ✨ Feat, 🎨 Design

#340 [fix] 이메일 중복검사 추가
  app/api/auth/send-email/route.ts
  app/api/signup/route.ts
  application/usecases/auth/DfCheckEmailDuplicationUsecase.ts
Labels: ✨ Feat

#348 [fix] 03/11 안 쓰는 코드 삭제
  components/header/Header.tsx
Labels: 🛠️ Fix

#349 [fix] 회원가입 빌드 에러 수정
  app/(main)/(anon)/signup/components/NicknameValidation.tsx
  app/api/auth/verify-code/route.ts
  application/usecases/auth/DfSendEmailUsecase.ts
Labels: 🛠️ Fix

#350 [fix] novel build error
  app/(main)/(anon)/novel/[novelId]/(episode)/[episodeId]/page.tsx
  app/(main)/user/novel/[novelId]/(episode)/[episodeId]/page.tsx
  app/(main)/user/novel/component/BannerCarousel.tsx
  app/(main)/user/novel/component/MyBook.tsx
  app/(main)/user/novel/component/SearchBook.tsx
  app/(main)/user/novel/component/SerialDayBook.tsx
  app/(main)/user/novel/component/Top10.tsx
  app/(main)/user/novel/component/comments/NovelReplyComment.tsx
  app/(main)/user/novel/create/page.tsx
  app/(main)/user/novel/serialize/[novelId]/page.tsx
  app/api/novel/banner/route.ts
  app/api/novel/like/route.ts
  app/api/novel/search/route.ts
  app/api/novel/serial-day/[day]/route.ts
  app/api/novel/top10/route.ts
  components/dropdown/Dropdown.tsx
  components/sidebar/Sidebar.tsx
  public/bookCover/1741678357057-사극.webp
Labels: 🛠️ Fix

#344 [design] funding completed 컴포넌트
  app/(main)/user/funding/components/FundingCompleted.styled.tsx
  app/(main)/user/funding/components/FundingCompleted.tsx
  public/image/funding-completed.svg
Labels: 🎨 Design

#351 [fix] 03/11 빌드 오류 수정 #343
  app/(main)/(anon)/login/LoginPage.styled.tsx
  app/(main)/(anon)/login/actions/loginProc.ts
  app/(main)/(anon)/login/page.tsx
  app/(main)/(anon)/page.styled.tsx
  app/(main)/(anon)/page.tsx
  app/(main)/user/components/LikedNovelList.tsx
  app/(main)/user/components/LikedPostList.tsx
  app/(main)/user/components/PostAndLikedListWrapper.styled.tsx
  app/(main)/user/components/ProfileInfo.tsx
  app/(main)/user/components/ProfileIntroduce.tsx
  app/(main)/user/components/ProfileNovelList.tsx
  app/(main)/user/components/ProfilePostList.tsx
  app/(main)/user/components/ProfileView.tsx
  app/admin/novel/page.tsx
  app/api/auth/verify/route.ts
  app/api/user/community/liked/route.ts
  app/api/user/community/route.ts
  app/api/user/count/route.ts
  app/api/user/delete/route.ts
  app/api/user/introduce/route.ts
  app/api/user/nickname/route.ts
  app/api/user/novel/liked/route.ts
  app/api/user/novel/route.ts
  app/api/user/profile-image/route.ts
  components/authInitializer/AuthInitializer.tsx
  components/textarea/Textarea.tsx
Labels: 🛠️ Fix

#352 [fix] 빌드 오류 수정 #343
  app/(main)/(anon)/community/[id]/page.tsx
  app/(main)/(anon)/community/create/page.tsx
  app/(main)/(anon)/community/page.tsx
  app/(main)/(anon)/novel/[novelId]/(episode)/[episodeId]/page.tsx
  app/(main)/(anon)/novel/[novelId]/page.tsx
  app/(main)/(anon)/novel/page.tsx
  app/(main)/user/funding/components/FundingCompleted.tsx
  app/admin/community/page.styled.tsx
  app/admin/community/page.tsx
  app/admin/user/page.tsx
  app/api/user/nickname/route.ts
  domain/entities/auth.ts
  domain/entities/communityComment.ts
  domain/entities/communityCommentLike.ts
  domain/entities/communityPost.ts
  domain/entities/communityPostGenre.ts
  domain/entities/communityPostLike.ts
  domain/entities/funding.ts
  domain/entities/fundingUser.ts
  domain/entities/genre.ts
  domain/entities/novel.ts
  domain/entities/novelComment.ts
  domain/entities/novelCommentLike.ts
  domain/entities/novelEpisode.ts
  domain/entities/novelGenre.ts
  domain/entities/novelLike.ts
  domain/entities/user.ts
  domain/repositories/CommunityPostGenreRepository.ts
  infrastructure/repositories/PrCommunityPostGenreRepository.ts
  store/page.tsx
Labels: 🛠️ Fix

#354 [refactor] 03/11 autor -> author 오타 수정 #353
  app/(main)/user/novel/component/comments/NovelComment.tsx
  app/(main)/user/novel/component/comments/NovelReplyComment.tsx
  components/comment/Comment.styled.tsx
  components/comment/Comment.tsx
  components/comment/ReplyComment.styled.tsx
  components/comment/ReplyComment.tsx
Labels: ♻️ Refactor

#330 펀딩 시작 UI
  app/user/funding/[novelId]/create/StartFunding.styled.tsx
  app/user/funding/[novelId]/create/page.tsx
  public/banner/manimBanner.svg
Labels: 🎨 Design

#361 Feat/359 funding be
  app/(main)/user/funding/[novelId]/FundingIntro.styled.tsx
  app/(main)/user/funding/[novelId]/create/StartFunding.styled.tsx
  app/(main)/user/funding/[novelId]/create/page.tsx
  app/(main)/user/funding/[novelId]/page.tsx
  app/(main)/user/funding/page.tsx
  package-lock.json
  package.json
Labels: 🛠️ Fix

#363 [setting] 포트 번호 변경 #362
  package.json
Labels: ⚙️ Setting

#365 [design] 빌드 에러 수정
  app/(main)/user/funding/page.tsx
Labels: 🎨 Design

#367 [fix] 03/12 파라미터 오류 수정 #357
  app/(main)/(anon)/login/actions/loginProc.ts
  app/(main)/(anon)/login/page.tsx
  app/(main)/user/novel/component/SerialDayBook.tsx
  app/api/community/[id]/route.ts
  app/api/community/comment/[id]/route.ts
  app/api/novel/[novelId]/route.ts
  app/api/novel/serial-day/[day]/route.ts
  middleware.ts
  utils/params/requestParams.ts
Labels: 🛠️ Fix

#368 [fix] 로그아웃 시 사용자 아이디 삭제 #357
  app/api/logout/route.ts
  application/usecases/auth/DfRefreshTokenUsecase.ts
Labels: 🛠️ Fix

#371 [setting] package.json port 제거 #370
  package.json
Labels: ⚙️ Setting

#372 [배포] develop -> main merge
  app/(main)/(anon)/login/actions/loginProc.ts
  app/(main)/(anon)/login/page.tsx
  app/(main)/user/funding/FundingList.styled.tsx
  app/(main)/user/funding/components/FundingBookList.styled.tsx
  app/(main)/user/funding/components/FundingBookListAll.tsx
  app/(main)/user/funding/components/FundingBookListStep1.tsx
  app/(main)/user/funding/components/FundingBookListStep2.styled.tsx
  app/(main)/user/funding/components/FundingBookListStep2.tsx
  app/(main)/user/funding/components/FundingBookListStep3.tsx
  app/(main)/user/funding/components/FundingSearch.tsx
  app/(main)/user/funding/page.tsx
  app/(main)/user/novel/component/SerialDayBook.tsx
  app/api/community/[id]/route.ts
  app/api/community/comment/[id]/route.ts
  app/api/logout/route.ts
  app/api/novel/[novelId]/route.ts
  app/api/novel/serial-day/[day]/route.ts
  application/usecases/auth/DfRefreshTokenUsecase.ts
  constants/FUNDING_SEARCH.ts
  middleware.ts
  package.json
  public/image/funding-step2.png
  public/image/funding-step3.png
  utils/params/requestParams.ts
Labels: 🌐 배포

#373 [fix] 03/12 build 중에 prisma 설정
  package.json
Labels: 🛠️ Fix

#374 [배포] devleop -> main 배포용 merge
  package.json
Labels: 🌐 배포

#377 [merge] develop -> main 배포 merge
  components/authInitializer/AuthInitializer.tsx
Labels: ➕Merge

#379 [fix] 소설 파라미터 수정 #357
  app/api/novel/[novelId]/[episodeId]/comments/[id]/like/route.ts
  app/api/novel/[novelId]/[episodeId]/comments/[id]/route.ts
  app/api/novel/[novelId]/[episodeId]/comments/route.ts
Labels: 🛠️ Fix

#390 [feat] 359 토스 페이먼츠 결제 후 성공 페이지 연결
  app/(main)/(anon)/funding/fail/page.tsx
  app/(main)/(anon)/funding/success/page.tsx
  app/(main)/user/funding/[novelId]/components/PaymentButton.tsx
  app/(main)/user/funding/[novelId]/create/page.tsx
  app/(main)/user/funding/[novelId]/page.tsx
  app/(main)/user/funding/components/FundingCompleted.styled.tsx
  app/(main)/user/funding/components/FundingModal.tsx
  app/api/funding/route.ts
Labels: ✨ Feat

#388 [feat] 회원 관리 구현 #337
  app/admin/AdminPage.styled.tsx
  app/admin/components/AdminSidebar.styled.tsx
  app/admin/novel/page.tsx
  app/admin/user/AdminUserPage.styled.tsx
  app/admin/user/components/DeleteUserButton.tsx
  app/admin/user/page.tsx
  app/api/admin/user/delete/[userId]/route.ts
  app/api/admin/user/route.ts
  app/globals.css
  application/usecases/funding/DfFundingStatusLengthByUserIdUsecase.ts
  application/usecases/user/DfFindAllUserUsecase.ts
  application/usecases/user/DfFindAllUserWithFundingStatus.ts
  application/usecases/user/dto/FindAllUser.ts
  domain/repositories/FundingRepository.ts
  infrastructure/repositories/PrFundingRepository.ts
  infrastructure/repositories/PrNovelEpisodeRepository.ts
  public/bookCover/1741831521062-26cc3cb82a30685eac0e153c7a49f0d6ab1e72678a54d7047ee95c6578ba68b2.png
  public/profileImage/920e5702-13bf-4dfa-a517-7fe4670d7364-IMG_4417.jpeg
Labels: ✨ Feat

#391 [merge] Develop -> Main 배포용 merge
  app/(main)/(anon)/funding/fail/page.tsx
  app/(main)/(anon)/funding/success/page.tsx
  app/(main)/user/funding/[novelId]/components/PaymentButton.tsx
  app/(main)/user/funding/[novelId]/create/page.tsx
  app/(main)/user/funding/[novelId]/page.tsx
  app/(main)/user/funding/components/FundingCompleted.styled.tsx
  app/(main)/user/funding/components/FundingModal.tsx
  app/admin/AdminPage.styled.tsx
  app/admin/components/AdminSidebar.styled.tsx
  app/admin/novel/page.tsx
  app/admin/user/AdminUserPage.styled.tsx
  app/admin/user/components/DeleteUserButton.tsx
  app/admin/user/page.tsx
  app/api/admin/user/delete/[userId]/route.ts
  app/api/admin/user/route.ts
  app/api/funding/route.ts
  app/globals.css
  application/usecases/funding/DfFundingStatusLengthByUserIdUsecase.ts
  application/usecases/user/DfFindAllUserUsecase.ts
  application/usecases/user/DfFindAllUserWithFundingStatus.ts
  application/usecases/user/dto/FindAllUser.ts
  domain/repositories/FundingRepository.ts
  infrastructure/repositories/PrFundingRepository.ts
  infrastructure/repositories/PrNovelEpisodeRepository.ts
  public/bookCover/1741831521062-26cc3cb82a30685eac0e153c7a49f0d6ab1e72678a54d7047ee95c6578ba68b2.png
  public/profileImage/920e5702-13bf-4dfa-a517-7fe4670d7364-IMG_4417.jpeg
Labels: ➕Merge

#393 [design] 펀딩 실패 페이지 UI #392
  app/(main)/(anon)/funding/fail/page.tsx
Labels: 🎨 Design

#394 [merge] Develop -> Main 배포용 merge
  app/(main)/(anon)/funding/fail/page.tsx
Labels: ➕Merge

#397 [remove] 사용하지 않는 파일 삭제 #395
  application/usecases/funding/DfFundingStatusLengthByUserIdUsecase.ts
  application/usecases/user/DfFindAllUserUsecase.ts
Labels: 🗑️ Remove

#398 [merge] Develop -> Main 배포용 merge
  app/(main)/(anon)/funding/success/page.tsx
  app/(main)/user/funding/components/FundingCompleted.tsx
  application/usecases/funding/DfFundingStatusLengthByUserIdUsecase.ts
  application/usecases/user/DfFindAllUserUsecase.ts
Labels: ➕Merge, 🌐 배포

#402 [!hotfix] community filter input 사이즈 수정 #401
  app/(main)/user/community/components/CommunitySearchFilter.tsx
Labels: 🚑 !HOTFIX, 🎨 Design

#403 [merge] Develop -> Main merge
  app/(main)/user/community/components/CommunitySearchFilter.tsx
Labels: ➕Merge, 🌐 배포

#406 [design] 03/17 top 10 리스트 어긋남 ui 수정 #405
  app/(main)/user/novel/component/Top10.styled.tsx
Labels: 🎨 Design

#408 [refactor] DI 컨테이너로 usecase 호출 #404
  app/api/admin/novel-episode/[episodeId]/route.ts
  app/api/admin/novel-episode/route.ts
  app/api/admin/user/delete/[userId]/route.ts
  app/api/admin/user/route.ts
  app/api/auth/verify/route.ts
  app/api/login/route.ts
  app/api/logout/route.ts
  app/api/user/community/liked/route.ts
  app/api/user/community/route.ts
  app/api/user/count/route.ts
  app/api/user/delete/route.ts
  app/api/user/introduce/route.ts
  app/api/user/nickname/route.ts
  app/api/user/novel/liked/route.ts
  app/api/user/novel/route.ts
  app/api/user/profile-image/route.ts
  application/usecases/auth/DfLoginUsecase.ts
  application/usecases/funding/DfGetFundingByNovelIdUsecase.ts
  application/usecases/novel/DfDeleteNovelByNovelIdUsecase.ts
  application/usecases/novel/DfDeleteNovelEpisodeByEpisodeIdUsecase.ts
  application/usecases/novel/DfGetLikedNovelsByUserIdUsecase.ts
  application/usecases/novel/DfGetNovelByUserIdUsecase.ts
  application/usecases/novel/DfUpdateNovelEpisodeStatusByEpisodeIdUsecase.ts
  application/usecases/novel/DfUpdateNovelSerialStatusByNovelIdUsecase.ts
  application/usecases/user/DfDeleteUserByUserIdUsecase.ts
  application/usecases/user/DfGetUserStatsByUserIdUsecase.ts
  application/usecases/user/DfUpdateIntroduceByUserIdUsecase.ts
  application/usecases/user/DfUpdateNicknameByUserIdUsecase.ts
  application/usecases/user/DfUpdateProfileImageByUserIdUsecase.ts
  infrastructure/config/adminDi.ts
  infrastructure/config/authDi.ts
  infrastructure/config/userDi.ts
Labels: ♻️ Refactor

#413 [refactor] 폰트 최적화
  app/fonts/pretendard.ts
  app/globals.css
  app/layout.tsx
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff2
  public/profileImage/8ba73da2-20bb-47a7-aa43-b6d811b2cfad-Group 2725.png
Labels: ♻️ Refactor, 🔨Chore

#418 [merge] Develop -> Main 배포용 merge
  app/(main)/user/community/components/CommunityPostList.styled.tsx
  app/(main)/user/community/components/CommunityPostList.tsx
  app/(main)/user/community/components/CommunitySearchFilter.styled.tsx
  app/(main)/user/community/components/skeleton/CommunityPostSkeleton.tsx
  app/(main)/user/community/components/skeleton/PostSkeleton.tsx
  app/(main)/user/novel/[novelId]/page.tsx
  app/(main)/user/novel/component/NovelLikeButton.tsx
  app/api/admin/novel-episode/[episodeId]/route.ts
  app/api/admin/novel-episode/route.ts
  app/api/admin/user/delete/[userId]/route.ts
  app/api/admin/user/route.ts
  app/api/auth/verify/route.ts
  app/api/login/route.ts
  app/api/logout/route.ts
  app/api/novel/[novelId]/route.ts
  app/api/user/community/liked/route.ts
  app/api/user/community/route.ts
  app/api/user/count/route.ts
  app/api/user/delete/route.ts
  app/api/user/introduce/route.ts
  app/api/user/nickname/route.ts
  app/api/user/novel/liked/route.ts
  app/api/user/novel/route.ts
  app/api/user/profile-image/route.ts
  app/fonts/pretendard.ts
  app/globals.css
  app/layout.tsx
  app/lib/registry.tsx
  application/usecases/auth/DfLoginUsecase.ts
  application/usecases/funding/DfGetFundingByNovelIdUsecase.ts
  application/usecases/novel/DfCheckNovelLikeStatusUsecase.ts
  application/usecases/novel/DfDeleteNovelByNovelIdUsecase.ts
  application/usecases/novel/DfDeleteNovelEpisodeByEpisodeIdUsecase.ts
  application/usecases/novel/DfGetLikedNovelsByUserIdUsecase.ts
  application/usecases/novel/DfGetNovelByUserIdUsecase.ts
  application/usecases/novel/DfUpdateNovelEpisodeStatusByEpisodeIdUsecase.ts
  application/usecases/novel/DfUpdateNovelSerialStatusByNovelIdUsecase.ts
  application/usecases/user/DfDeleteUserByUserIdUsecase.ts
  application/usecases/user/DfGetUserStatsByUserIdUsecase.ts
  application/usecases/user/DfUpdateIntroduceByUserIdUsecase.ts
  application/usecases/user/DfUpdateNicknameByUserIdUsecase.ts
  application/usecases/user/DfUpdateProfileImageByUserIdUsecase.ts
  domain/repositories/NoveLikeRepository.ts
  infrastructure/config/adminDi.ts
  infrastructure/config/authDi.ts
  infrastructure/config/novelDi.ts
  infrastructure/config/userDi.ts
  infrastructure/repositories/PrNovelLikeRepository.ts
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff2
  public/profileImage/8ba73da2-20bb-47a7-aa43-b6d811b2cfad-Group 2725.png
Labels: ➕Merge

#419 [Fix] 이미지 저장 스토리지 public에서 aws s3로 변경
  application/usecases/user/DfDeleteUserByUserIdUsecase.ts
  infrastructure/services/FileService.ts
  next.config.ts
  package-lock.json
  package.json
Labels: 🛠️ Fix
